import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="h-96 bg-zinc-400">
        サイトタイトル<br />
        駆け出しエンジニアの備忘録です<br />
        入力アニメーション
        （カテゴリ等）
        背景：3Dアニメーション
      </section>
      <section className="h-96">新着</section>
      <div className="h-96">自己紹介</div>
      <div className="h-96">Twitterカード</div>
      <div className="h-96">タグ一覧</div>
    </>
  )
}
